[package]
name = "adbcat"
version = "0.1.0"
authors = ["Joakim Hulthe <joakim@hulthe.net>"]
edition = "2018"

[dependencies]
tui = "0.8.0"
termion = "1.5.5"
tokio = { version = "0.2.13", features = ["full"] }
futures = "0.3.4"
regex = "1.3.5"
lazy_static = "1.4.0"
structopt = "0.3.12"
